name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - bazzite
          - kinoite

    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install just
        run: sudo apt update && apt install -y just

      - name: Build image-builder container
        run: sudo just build-image-builder

      - name: Build ${{ matrix.container }} container
        run: sudo just container ${{ matrix.container }}

      - name: Build ${{ matrix.container }} ISO
        run: sudo just iso-in-container ${{ matrix.container }}
